### PR TITLE
show navbar on cursor hover on tabs

### PR DESCRIPTION
**Pull request by sewnie**
i would like to access my navbar without going to a new tab, so this patch allows the navbar to appear when the cursor is hovered over the tabs/titlebar/toolbar.

### CODE REVIEW

**Comment by Dook97** [comment]
Thanks. I actually had this configured like a year ago, but it seemed clanky to me so I removed it. I guess I could make it so that enabling this would be just a matter of uncommenting a line of code.

**Comment by sewnie** [comment]
I've noticed the search suggestions are hidden, which is why i marked this PR as WIP, is this intentional?

**Comment by Dook97** [comment]
> I've noticed the search suggestions are hidden, which is why i marked this PR as WIP, is this intentional?

[Yes](https://github.com/Dook97/firefox-qutebrowser-userchrome/blob/e7612ab419dc03f5a9512fc7d637347b5421b688/userChrome.css#L33). Though I think the autohide feature also messes with the suggestions somehow.

**Comment by sewnie** [comment]
> Though I think the autohide feature also messes with the suggestions somehow.

Seems not the case, that part of the CSS does nothing. The only reason autocomplete is hidden is due to the 'AUTOHIDE NAVBAR' section - if it were removed, autocomplete shows fine, regardless of that autocomplete hiding.

**Comment by Dook97** [comment]
> > Though I think the autohide feature also messes with the suggestions
> > somehow.
>
> Seems not the case, that part of the CSS does nothing. The only reason
> autocomplete is hidden is due to the 'AUTOHIDE NAVBAR' section - if it were
> removed, autocomplete shows fine, regardless of that autocomplete hiding.

Ok. I actually have autocomplete disabled via user.js, so I wouldn't notice
either way :) Guess there were some breaking changes in ff since I wrote that.

Anyway if you figure out a way to have auto-hiding work with urlbar suggestions
still being available I will merge it. I don't care for it, but iirc someone
asked me about it previously so I guess some people find it useful.

**Comment by sewnie** [comment]
> Anyway if you figure out a way to have auto-hiding work with urlbar suggestions
> [...]

In the context of this repository, it is disabled (and will be disabled anyway), so it is pointless to make a workaround.

**Comment by Dook97** [comment]
> > Anyway if you figure out a way to have auto-hiding work with urlbar
> > suggestions [...]
>
> In the context of this repository, it is disabled (and will be disabled
> anyway), so it is pointless to make a workaround.

Not really. I originally had that snippet which disabled it because I didn't know
that it could be achieved via user.js. Now I would have no problem with it not
being hidden by the userchrome.

But ofc if you don't feel like working on it, that's not a problem. I just
thought it's something maybe you would like for yourself and others who find it
useful.

**Pull request merged**
